// Package rules contiene la definición de las 36 Security Verification Rules
// (catalog.go) y la lógica de validación que las contrasta contra la evidencia
// recopilada por el módulo de descubrimiento (validators.go).
package rules

import (
	ctx "github.com/stagingshield/staging-shield/internal/context"
)

// Catalog devuelve las 36 SVR del modelo, en el orden canónico del documento.
// El campo Critical marca aquellas reglas cuyo incumplimiento bloquea la
// promoción del entorno (condición de aptitud complementaria).
func Catalog() []ctx.SVR {
	return []ctx.SVR{
		// =================== Dominio 1: Red y aislamiento ===================
		{
			ID:        "SVR-NET-01",
			Domain:    ctx.DomainNet,
			Criterion: "El entorno de staging debe estar segmentado de producción mediante controles de red definidos.",
			Evidence:  "Diagrama de red, reglas de firewall, tablas de rutas, ACL o security groups.",
			Method:    "Revisión de arquitectura y prueba de conectividad controlada desde staging hacia activos de producción.",
			Severity:  ctx.SevAlta,
			Reference: "NIST SC-7",
			Mode:      ctx.ModeSemiAutomatic,
			Critical:  true,
		},
		{
			ID:        "SVR-NET-02",
			Domain:    ctx.DomainNet,
			Criterion: "Todo tráfico entrante y saliente debe pasar por interfaces gestionadas.",
			Evidence:  "Topología del entorno, configuración de firewall, gateway o reverse proxy.",
			Method:    "Revisión de arquitectura y validación del flujo de tráfico.",
			Severity:  ctx.SevAlta,
			Reference: "NIST SC-7(a)",
			Mode:      ctx.ModeManual,
			Critical:  true,
		},
		{
			ID:        "SVR-NET-03",
			Domain:    ctx.DomainNet,
			Criterion: "Los servicios expuestos públicamente deben estar en una subred o segmento separado.",
			Evidence:  "Diagrama de subredes, VLAN, DMZ o segmentación lógica.",
			Method:    "Revisión documental y análisis de segmentación.",
			Severity:  ctx.SevAlta,
			Reference: "NIST SC-7(b)",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},
		{
			ID:        "SVR-NET-04",
			Domain:    ctx.DomainNet,
			Criterion: "El número de conexiones externas debe limitarse al mínimo necesario.",
			Evidence:  "Inventario de puertos abiertos, reglas de firewall y dependencias externas.",
			Method:    "Escaneo de puertos y contraste con los puertos declarados por el responsable del entorno.",
			Severity:  ctx.SevAlta,
			Reference: "NIST SC-7(c)",
			Mode:      ctx.ModeAutomatic,
			Critical:  true,
		},
		{
			ID:        "SVR-NET-05",
			Domain:    ctx.DomainNet,
			Criterion: "El perímetro debe operar con política de denegación por defecto para tráfico entrante.",
			Evidence:  "Configuración de firewall perimetral o del balanceador.",
			Method:    "Revisión de reglas y validación de exposición real.",
			Severity:  ctx.SevAlta,
			Reference: "NIST SC-7(5)",
			Mode:      ctx.ModeSemiAutomatic,
			Critical:  true,
		},
		{
			ID:        "SVR-NET-06",
			Domain:    ctx.DomainNet,
			Criterion: "No debe haber túneles, rutas o integraciones no documentadas entre staging y otros entornos.",
			Evidence:  "Inventario de integraciones, túneles, VPN y rutas.",
			Method:    "Revisión de arquitectura y validación con el responsable del entorno.",
			Severity:  ctx.SevAlta,
			Reference: "NIST SC-7",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},
		{
			ID:        "SVR-NET-07",
			Domain:    ctx.DomainNet,
			Criterion: "Los servicios expuestos deben usar TLS 1.3 cuando la naturaleza del servicio lo requiera.",
			Evidence:  "Certificado, configuración TLS y respuesta del servicio.",
			Method:    "Prueba de conexión HTTPS o TLS 1.3 y revisión de parámetros básicos del canal.",
			Severity:  ctx.SevMedia,
			Reference: "NIST SC-8",
			Mode:      ctx.ModeAutomatic,
			Critical:  false,
		},
		{
			ID:        "SVR-NET-08",
			Domain:    ctx.DomainNet,
			Criterion: "Las interfaces administrativas no deben estar expuestas libremente a internet.",
			Evidence:  "Lista de interfaces administrativas, reglas de acceso, segmentación o control de identidad.",
			Method:    "Revisión de exposición externa y validación de restricciones de acceso.",
			Severity:  ctx.SevAlta,
			Reference: "NIST SC-7(a)",
			Mode:      ctx.ModeAutomatic,
			Critical:  true,
		},
		{
			ID:        "SVR-NET-09",
			Domain:    ctx.DomainNet,
			Criterion: "Las reglas de firewall deben coincidir con los puertos esperados declarados por el usuario.",
			Evidence:  "Puertos esperados, reglas efectivas, resultado del escaneo.",
			Method:    "Comparación entre la entrada del programa cliente y la superficie expuesta detectada.",
			Severity:  ctx.SevMedia,
			Reference: "CIS Benchmarks",
			Mode:      ctx.ModeAutomatic,
			Critical:  false,
		},
		{
			ID:        "SVR-NET-10",
			Domain:    ctx.DomainNet,
			Criterion: "Los componentes públicos no deben compartir una red plana con servicios internos críticos.",
			Evidence:  "Topología del entorno y rutas entre frontend y servicios internos.",
			Method:    "Revisión de segmentación y validación del flujo entre componentes.",
			Severity:  ctx.SevAlta,
			Reference: "NIST SC-7(b)",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},

		// =================== Dominio 2: Hardening ===================
		{
			ID:        "SVR-HAR-01",
			Domain:    ctx.DomainHar,
			Criterion: "El sistema operativo debe cumplir al menos el nivel uno del CIS Benchmark aplicable.",
			Evidence:  "Reporte de benchmark, checklist de hardening o salida de herramienta equivalente.",
			Method:    "Comparación de la configuración real con la línea base CIS correspondiente.",
			Severity:  ctx.SevAlta,
			Reference: "CIS Level 1 Benchmark",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},
		{
			ID:        "SVR-HAR-02",
			Domain:    ctx.DomainHar,
			Criterion: "Los servicios innecesarios deben estar deshabilitados.",
			Evidence:  "Listado de servicios activos y justificación funcional.",
			Method:    "Inspección del host y contraste con el rol declarado del entorno.",
			Severity:  ctx.SevMedia,
			Reference: "CIS §2.1–2.2",
			Mode:      ctx.ModeSemiAutomatic,
			Critical:  false,
		},
		{
			ID:        "SVR-HAR-03",
			Domain:    ctx.DomainHar,
			Criterion: "El acceso administrativo remoto debe estar endurecido.",
			Evidence:  "Configuración de SSH, RDP u otro mecanismo administrativo.",
			Method:    "Revisión de parámetros de acceso remoto y validación de configuración segura.",
			Severity:  ctx.SevAlta,
			Reference: "CIS §5.2 (SSH Hardening)",
			Mode:      ctx.ModeSemiAutomatic,
			Critical:  false,
		},
		{
			ID:        "SVR-HAR-04",
			Domain:    ctx.DomainHar,
			Criterion: "El host debe estar actualizado a un nivel aceptable de parches.",
			Evidence:  "Listado de paquetes, versión del sistema y estado de actualización.",
			Method:    "Revisión del estado de paquetes y contraste con la política definida.",
			Severity:  ctx.SevAlta,
			Reference: "NIST SI-2",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},
		{
			ID:        "SVR-HAR-05",
			Domain:    ctx.DomainHar,
			Criterion: "El firewall local del host debe estar activo cuando sea necesario.",
			Evidence:  "Configuración del firewall del sistema y reglas activas.",
			Method:    "Inspección del host y validación del servicio de filtrado local.",
			Severity:  ctx.SevMedia,
			Reference: "CIS §3.5",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},
		{
			ID:        "SVR-HAR-06",
			Domain:    ctx.DomainHar,
			Criterion: "El servidor web no debe exponer firmas, banners ni directorios innecesarios.",
			Evidence:  "Respuesta HTTP, configuración del servidor web y módulos activos.",
			Method:    "Análisis de encabezados y revisión de configuración del servidor.",
			Severity:  ctx.SevMedia,
			Reference: "CIS Web Server Benchmark",
			Mode:      ctx.ModeAutomatic,
			Critical:  false,
		},
		{
			ID:        "SVR-HAR-07",
			Domain:    ctx.DomainHar,
			Criterion: "Los módulos, extensiones o plugins no utilizados deben estar deshabilitados.",
			Evidence:  "Listado de módulos activos y finalidad del entorno.",
			Method:    "Revisión de módulos habilitados frente al uso real del sistema.",
			Severity:  ctx.SevMedia,
			Reference: "CIS Web Server Benchmark",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},
		{
			ID:        "SVR-HAR-08",
			Domain:    ctx.DomainHar,
			Criterion: "Los permisos exagerados sobre archivos y directorios sensibles se deben reducir a lo mínimo requerido.",
			Evidence:  "Permisos de rutas críticas, usuarios propietarios y grupos asociados.",
			Method:    "Inspección de permisos y contraste con criterios mínimos de seguridad.",
			Severity:  ctx.SevAlta,
			Reference: "CIS §6.1–6.2",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},
		{
			ID:        "SVR-HAR-09",
			Domain:    ctx.DomainHar,
			Criterion: "El entorno debe restringir servicios heredados o protocolos innecesarios.",
			Evidence:  "Listado de procesos, puertos y protocolos activos.",
			Method:    "Análisis de servicios en ejecución y revisión de necesidad operativa.",
			Severity:  ctx.SevMedia,
			Reference: "CIS §2.2",
			Mode:      ctx.ModeAutomatic,
			Critical:  false,
		},
		{
			ID:        "SVR-HAR-10",
			Domain:    ctx.DomainHar,
			Criterion: "La configuración base debe permitir trazabilidad de cambios relevantes.",
			Evidence:  "Configuración de auditoría, logs del sistema o mecanismos equivalentes.",
			Method:    "Revisión de mecanismos de logging administrativo y evidencias generadas.",
			Severity:  ctx.SevMedia,
			Reference: "CIS §4.1 / NIST AU-2",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},

		// =================== Dominio 3: Identidades, acceso y secretos ===================
		{
			ID:        "SVR-IAM-01",
			Domain:    ctx.DomainIam,
			Criterion: "Las credenciales de staging no deben reutilizarse en producción.",
			Evidence:  "Inventario de cuentas, roles, llaves y tokens por entorno.",
			Method:    "Revisión documental y validación de separación de credenciales.",
			Severity:  ctx.SevAlta,
			Reference: "NIST IA-5",
			Mode:      ctx.ModeManual,
			Critical:  true,
		},
		{
			ID:        "SVR-IAM-02",
			Domain:    ctx.DomainIam,
			Criterion: "Los usuarios administrativos del entorno deben limitarse al mínimo necesario.",
			Evidence:  "Listado de usuarios con privilegios y justificación de acceso.",
			Method:    "Revisión de cuentas privilegiadas y contraste con funciones asignadas.",
			Severity:  ctx.SevAlta,
			Reference: "NIST AC-6",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},
		{
			ID:        "SVR-IAM-03",
			Domain:    ctx.DomainIam,
			Criterion: "Las cuentas de servicio deben tener permisos específicos para el entorno evaluado.",
			Evidence:  "Inventario de cuentas de servicio y permisos asociados.",
			Method:    "Revisión de privilegios efectivos y evaluación de excesos de permisos.",
			Severity:  ctx.SevAlta,
			Reference: "NIST AC-6(1)",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},
		{
			ID:        "SVR-IAM-04",
			Domain:    ctx.DomainIam,
			Criterion: "Los secretos del entorno no deben estar embebidos en código fuente o archivos públicos.",
			Evidence:  "Archivos de configuración, variables de entorno, repositorio local y resultados de detección de secretos.",
			Method:    "Búsqueda controlada en rutas definidas por el usuario y revisión de exposiciones evidentes.",
			Severity:  ctx.SevAlta,
			Reference: "NIST SC-28",
			Mode:      ctx.ModeAutomatic,
			Critical:  true,
		},
		{
			ID:        "SVR-IAM-05",
			Domain:    ctx.DomainIam,
			Criterion: "Las interfaces administrativas deben exigir autenticación robusta cuando aplique.",
			Evidence:  "Método de autenticación configurado y evidencia de protección del panel o consola.",
			Method:    "Revisión funcional del acceso y análisis del mecanismo de autenticación.",
			Severity:  ctx.SevAlta,
			Reference: "NIST IA-2",
			Mode:      ctx.ModeSemiAutomatic,
			Critical:  false,
		},
		{
			ID:        "SVR-IAM-06",
			Domain:    ctx.DomainIam,
			Criterion: "El entorno debe diferenciar usuarios técnicos de usuarios funcionales.",
			Evidence:  "Inventario de cuentas, perfiles y uso esperado.",
			Method:    "Análisis de separación de funciones y revisión de cuentas compartidas.",
			Severity:  ctx.SevMedia,
			Reference: "NIST AC-5",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},
		{
			ID:        "SVR-IAM-07",
			Domain:    ctx.DomainIam,
			Criterion: "Las variables sensibles deben cargarse desde mecanismos apropiados y no desde archivos expuestos.",
			Evidence:  "Archivos de configuración, mecanismos de carga de variables y rutas sensibles.",
			Method:    "Revisión de configuración local y detección de exposición en ubicaciones inseguras.",
			Severity:  ctx.SevAlta,
			Reference: "NIST SC-28",
			Mode:      ctx.ModeAutomatic,
			Critical:  false,
		},
		{
			ID:        "SVR-IAM-08",
			Domain:    ctx.DomainIam,
			Criterion: "El acceso desde redes externas hacia recursos internos debe asociarse a identidades autorizadas.",
			Evidence:  "Configuración de acceso, reglas de identidad y evidencias de control de acceso.",
			Method:    "Revisión de políticas y validación de protección de componentes críticos.",
			Severity:  ctx.SevMedia,
			Reference: "NIST AC-17",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},

		// =================== Dominio 4: Monitoreo, integridad y trazabilidad ===================
		{
			ID:        "SVR-MON-01",
			Domain:    ctx.DomainMon,
			Criterion: "El entorno debe generar logs de acceso, error y administración.",
			Evidence:  "Archivos de log, salida de plataforma o consola de registros.",
			Method:    "Revisión de existencia, tipo y utilidad mínima de los registros generados.",
			Severity:  ctx.SevMedia,
			Reference: "NIST AU-2",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},
		{
			ID:        "SVR-MON-02",
			Domain:    ctx.DomainMon,
			Criterion: "Los servicios de frontera deben registrar tráfico relevante.",
			Evidence:  "Logs del firewall, reverse proxy, WAF o balanceador.",
			Method:    "Revisión de eventos y validación de que el tráfico relevante queda trazado.",
			Severity:  ctx.SevMedia,
			Reference: "NIST AU-3",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},
		{
			ID:        "SVR-MON-03",
			Domain:    ctx.DomainMon,
			Criterion: "El entorno debe conservar evidencia suficiente para investigar cambios de configuración.",
			Evidence:  "Historial de cambios, logs administrativos o evidencia equivalente.",
			Method:    "Revisión de mecanismos de trazabilidad sobre cambios críticos.",
			Severity:  ctx.SevMedia,
			Reference: "NIST AU-11",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},
		{
			ID:        "SVR-MON-04",
			Domain:    ctx.DomainMon,
			Criterion: "Deben detectarse cambios no autorizados en archivos o configuraciones sensibles cuando el entorno lo permita.",
			Evidence:  "Salida de herramientas de integridad o evidencia de verificación periódica.",
			Method:    "Revisión del mecanismo de integridad y del alcance de monitoreo.",
			Severity:  ctx.SevMedia,
			Reference: "NIST SI-7",
			Mode:      ctx.ModeManual,
			Critical:  false,
		},
		{
			ID:        "SVR-MON-05",
			Domain:    ctx.DomainMon,
			Criterion: "La evaluación del entorno debe producir historial comparable en el tiempo.",
			Evidence:  "Resultados de evaluaciones anteriores o almacenamiento local de corridas.",
			Method:    "Revisión de persistencia local y comparación entre reportes.",
			Severity:  ctx.SevBaja,
			Reference: "Buena práctica",
			Mode:      ctx.ModeAutomatic,
			Critical:  false,
		},
		{
			ID:        "SVR-MON-06",
			Domain:    ctx.DomainMon,
			Criterion: "El sistema debe alertar cuando falle una regla crítica del perímetro o del aislamiento.",
			Evidence:  "Reporte final con marcación de hallazgos críticos.",
			Method:    "Revisión del mecanismo de alertamiento y de la salida del programa.",
			Severity:  ctx.SevAlta,
			Reference: "NIST SC-7 / AU-5",
			Mode:      ctx.ModeAutomatic,
			Critical:  false,
		},
		{
			ID:        "SVR-MON-07",
			Domain:    ctx.DomainMon,
			Criterion: "El reporte debe incluir score por dominio y score global.",
			Evidence:  "Reporte generado por la herramienta.",
			Method:    "Revisión del formato de salida y validación del cálculo agregado.",
			Severity:  ctx.SevBaja,
			Reference: "Buena práctica",
			Mode:      ctx.ModeAutomatic,
			Critical:  false,
		},
		{
			ID:        "SVR-MON-08",
			Domain:    ctx.DomainMon,
			Criterion: "El reporte final debe enumerar evidencias faltantes y reglas no verificables de forma automática.",
			Evidence:  "Salida del sistema y registro de verificaciones incompletas.",
			Method:    "Revisión del reporte final y validación de diferenciación entre no cumple y falta de evidencia.",
			Severity:  ctx.SevMedia,
			Reference: "Buena práctica",
			Mode:      ctx.ModeAutomatic,
			Critical:  false,
		},
	}
}
